{
  try {
    return internalMap(e);
  }
 catch (  RuntimeException e2) {
    logger.error("unexpected exception when handling another exception: " + e.getMessage(),e);
    return new ErrorCodeRequestHandler(500);
  }
}
