{
  try {
    in.reset();
  }
 catch (  final IOException e) {
    handleIOException(e);
  }
}
